#Get Machine Certificate
$PersThumb = (Get-ChildItem -Path Cert:\LocalMachine\My | Where-Object {$_.Subject -match "DoD"}).Thumbprint
#Get RDP Thumbprint
$RDPThumb = (gwmi -class "Win32_TSGeneralSetting" -Namespace root\cimv2\terminalservices -filter "TerminalName='RDP-tcp'").SSLCertificateSHA1Hash

#Function called by comparisons at the end.
Function ChangeRDPCert { 

# Get config instance
$tsgs = gwmi -class "Win32_TSGeneralSetting" -Namespace root\cimv2\terminalservices -filter "TerminalName='RDP-tcp'"

#Get SSL Thumbprint
#This section depricated by $PersThumb variable above.
#$thumb = (gci -path cert:/LocalMachine/My | select -first 1).Thumbprint

#Set RDP Cert to Thumbprint
swmi -path $tsgs.__path -argument @{SSLCertificateSHA1Hash="$PersThumb"}

#Remove RDP cert. But it will be automatically regenerated by the OS.
Get-ChildItem -Path 'Cert:\localmachine\Remote Desktop' | Remove-Item

}

#Exit Script if there is no DoD certificate
if ($PersThumb -eq $null){
    
    exit
}

#Exit Script if the RDP configuration is correct
else{

    if ($PersThumb -eq $RDPThumb) {

        Exit

    }
#Call function if needed
    else{
    
        ChangeRDPCert
        Exit

    }
    }